[versions]
cicdtest = "0.0.1"
agp = "8.2.2"
kotlin = "1.9.22"

[libraries]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }