# This is a basic workflow to help you get started with Actions

name: Publishing an Android Library to JitPack 

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_release"
  create_release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Print current path
        run: pwd

      - name: List files
        run: ls -la

      - name: Extract version from Libs.versions.toml
        id: extract_version
        run: |
          version=$(grep 'cicdtest' ./gradle/libs.versions.toml | awk -F ' = ' '{print $2}' | tr -d '"')
          echo "::set-output name=version::$version"

      - name: Set up Git
        run: |
          git config user.name "EunhaKyeongAuto"
          git config user.email "ehkyeong.auto@gmail.com"

      - name: Create Tag
        run: |
          git tag ${{ steps.extract_version.outputs.version }}
          git push origin ${{ steps.extract_version.outputs.version }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            Changes in this release:
            ${{ github.event.pull_request.title }}
          draft: false
          prerelease: true
